In [60]:
from sklearn import svm
from sklearn.decomposition import PCA
from skimage.transform import resize
from skimage.io import imread
import pathlib

#import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split,GridSearchCV
import datetime
from sklearn.metrics import confusion_matrix,accuracy_score, classification_report
from PIL import Image
from sklearn.decomposition import PCA
from skimage.transform import resize
from skimage.io import imread
from sklearn import metrics

In [61]:
IMAGE_WIDTH = 128
IMAGE_HEIGHT = IMAGE_WIDTH
IMAGE_DEPTH = 3

# allow to build our image database
def build_image_database(path, target, encoding='UTF-8'):
    """Build a pandas dataframe with target class and access path to images.

    Parameters
    - - - - - -
    path (Path): path patern to read csv file containing images information.
    target (str): name of the target column.

    Returns
    - - - - -
    A pandas dataframe, including target class and path to image.
    """


    _df = pd.read_csv(path, sep=';', dtype={'all': str}, encoding=encoding)


    _df['path'] = _df['id'].apply(lambda x:  pathlib.Path(r'data_facture/all_facture') / (str(x) + '.png'))

    return _df

In [62]:
def build_x_svm_and_y_svm(df:pd.DataFrame,target:str,images:str,stratify=None):
  """Build x tensor and y tensor for model fitting

  Parameters
  --------------
  df(pd.DataFrame):dataframe contanining images and target
  target(str):name of target column
  images(str): name of images column

  Returns
  ---------
  x(np.array):tensor of x values
  y(np.array):name of y values
  """
  x = pd.DataFrame(np.array([img for img in df[images]]))
  y = df[target].astype('category').cat.codes


  return x, y

In [63]:
def load_resize(path,height,width):
  """Load an image and resize it to the target size
    Parameters
    --------
    path(Path): access path to image file
    height(int): resize image to this height
    width(int):resize image to this width

    Returns
    ----------
    nb.array containing resize


  """
  #np.array(Image.open(path).convert('RGB').resize((width, height))), (resize(imread(path)/255,(width,height))).flatten()
  return (resize(imread(path)/255,(width,height))).flatten()

In [64]:
# Load train & test dataset

train_df= build_image_database('data_facture/data_train.csv','label')
test_df= build_image_database('data_facture/data_test1.csv','label')

train_df['resized_image']=train_df.apply(lambda r:load_resize(r['path'],IMAGE_HEIGHT,IMAGE_WIDTH),axis=1)

test_df['resized_image']=test_df.apply(lambda r:load_resize(r['path'],IMAGE_HEIGHT,IMAGE_WIDTH),axis=1)

X_train,y_train  =build_x_svm_and_y_svm(train_df,'label','resized_image')
X_test,y_test =build_x_svm_and_y_svm(test_df,'label','resized_image')

In [65]:
X_train.describe()

,0,1,2,3,4,5,6,7,8,9,...,49142,49143,49144,49145,49146,49147,49148,49149,49150,49151
count,1040.000000,1040.000000,1040.000000,1040.000000,1040.000000,1040.000000,1040.000000,1040.000000,1040.000000,1040.000000,...,1040.000000,1040.000000,1040.000000,1040.000000,1040.000000,1040.000000,1040.000000,1040.000000,1040.000000,1040.000000
mean,0.875623,0.875948,0.876465,0.922672,0.923072,0.923583,0.925179,0.925604,0.926167,0.924551,...,0.924625,0.919622,0.920111,0.920762,0.914811,0.915285,0.915906,0.867180,0.867655,0.868180
std,0.178033,0.177680,0.177404,0.155674,0.155129,0.154704,0.157080,0.156574,0.156078,0.163647,...,0.177439,0.183099,0.182398,0.181585,0.187681,0.187000,0.186219,0.208552,0.208053,0.207406
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.815076,0.815076,0.815076,0.921716,0.922091,0.922091,0.924626,0.924626,0.926669,0.925196,...,0.941220,0.933956,0.934207,0.934207,0.925060,0.925965,0.925965,0.815242,0.815242,0.815242
50%,0.946790,0.946790,0.947837,0.986956,0.986956,0.986956,0.993699,0.993699,0.993852,0.994911,...,1.000000,0.999998,0.999998,0.999998,0.994754,0.994754,0.994754,0.960653,0.960653,0.960602
75%,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [66]:
train_df

,id,label,path,resized_image
0,100sharp,non_modifier,data_facture\all_facture\100sharp.png,"[0.9886480985066252, 0.9897114556558665, 0.989..."
1,101sharp,non_modifier,data_facture\all_facture\101sharp.png,"[0.6722224142935738, 0.6722224142935738, 0.672..."
2,102sharp,non_modifier,data_facture\all_facture\102sharp.png,"[0.8476499264970692, 0.8476499264970692, 0.847..."
3,103sharp,non_modifier,data_facture\all_facture\103sharp.png,"[0.9280412950948362, 0.9280412950948362, 0.928..."
4,104sharp,non_modifier,data_facture\all_facture\104sharp.png,"[0.9999999999999999, 0.9999999999999999, 0.999..."
...,...,...,...,...
1035,566blur,modifier,data_facture\all_facture\566blur.png,"[0.039398168769816465, 0.039398168769816465, 0..."
1036,567blur,modifier,data_facture\all_facture\567blur.png,"[0.998881330755312, 0.998881330755312, 0.99888..."
1037,568blur,modifier,data_facture\all_facture\568blur.png,"[0.8851928654455655, 0.8851928654455655, 0.885..."
1038,569blur,modifier,data_facture\all_facture\569blur.png,"[0.899873431644744, 0.899873431644744, 0.89987..."
1039,56blur,modifier,data_facture\all_facture\56blur.png,"[0.0, 0.0, 0.0, 1.2111392268893146e-05, 1.2111..."

In [67]:
test_df.head()

,id,label,path,resized_image
0,56sharp,non_modifier,data_facture\all_facture\56sharp.png,"[0.9999999999999999, 0.9999999999999999, 0.999..."
1,570sharp,non_modifier,data_facture\all_facture\570sharp.png,"[0.9999999999999996, 0.9999999999999996, 0.999..."
2,571sharp,non_modifier,data_facture\all_facture\571sharp.png,"[0.9526021392538435, 0.9526021392538435, 0.952..."
3,572sharp,non_modifier,data_facture\all_facture\572sharp.png,"[0.8087563837576436, 0.8087563837576436, 0.808..."
4,573sharp,non_modifier,data_facture\all_facture\573sharp.png,"[0.6974241636581743, 0.6974241636581743, 0.697..."

In [68]:
# Defining the parameters grid for GridSearchCV
param_grid={'C':[0.1, 1, 10, 100, 1000, 10000, 100000],
            'kernel':['rbf', 'sigmoid', 'linear', 'poly']}

# Creating a support vector classifier
svc=svm.SVC(probability=True)

# Creating a model using GridSearchCV with the parameters grid
model=GridSearchCV(svc,param_grid)

In [69]:
l=[]
for i in range(len(train_df)):
  l.append([x for x in train_df.loc[i, "resized_image"]])

In [70]:
d= pd.DataFrame(l)

In [71]:
d

,0,1,2,3,4,5,6,7,8,9,...,49142,49143,49144,49145,49146,49147,49148,49149,49150,49151
0,0.988648,0.989711,0.989314,0.952524,0.961559,0.958304,0.960521,0.971925,0.967774,0.963156,...,0.882262,0.716754,0.716773,0.716766,0.777998,0.777998,0.777998,0.981427,0.981427,0.981427
1,0.672222,0.672222,0.672222,0.987000,0.987000,0.987000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
2,0.847650,0.847650,0.847650,0.997901,0.997901,0.997901,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
3,0.928041,0.928041,0.928041,0.954272,0.954272,0.954272,0.962062,0.962062,0.962062,0.960936,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
4,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1035,0.039398,0.039398,0.039398,0.039417,0.039417,0.039417,0.039523,0.039523,0.039523,0.039890,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
1036,0.998881,0.998881,0.998881,0.999987,0.999987,0.999987,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,0.999332,0.999332,0.999332,0.943050,0.943050,0.943050
1037,0.885193,0.885193,0.885193,0.998642,0.998642,0.998642,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,0.998696,0.998696,0.998696,0.889085,0.889085,0.889085
1038,0.899873,0.899873,0.899873,0.998434,0.998434,0.998434,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,0.997741,0.997741,0.997741,0.886618,0.886618,0.886618
1039,0.000000,0.000000,0.000000,0.000012,0.000012,0.000012,0.001280,0.001280,0.001280,0.012197,...,0.633988,0.619289,0.619289,0.619289,0.551513,0.551513,0.551513,0.445263,0.445263,0.445263

In [72]:
d=d.dropna(axis=1)

In [73]:
pca = PCA(n_components=11)

In [74]:
pca.fit(d)

PCA(n_components=11)

In [75]:
pca.explained_variance_ratio_.sum()

0.5238402199639929

In [76]:
X_train_svm = pca.transform(d)

In [ ]:
model.fit(X_train_svm,y_train)

In [ ]:
model.best_params_

In [ ]:
m=[]
for i in range(len(test_df)):
  m.append([x for x in test_df.loc[i, "resized_image"]])

In [ ]:
m= pd.DataFrame(m)

In [ ]:
m=m.dropna(axis=1)

In [ ]:
m

In [ ]:
X_test = pca.transform(m)

In [ ]:
y_pred = model.predict(X_test)

In [ ]:
accuracy = accuracy_score(y_pred, y_test)

In [ ]:
accuracy

In [ ]:
classification = classification_report(y_test, y_pred)

In [ ]:
print(classification)

In [ ]:
metrics.confusion_matrix(y_pred, y_test)

In [ ]:
import datetime
def save_model(model, basename):
  """Save tf/Keras model

  Model file is named model + timestamp.

  Parameters
  ----------
  model (tf/Keras model): model to be saved
  basename: location to save model file
  """
  model('{}.sav'.format(basename))
  return

In [ ]:
filename = 'model_vgg/model.sav'

In [ ]:
import pickle

In [ ]:
pickle.dump(model, open(filename,"wb"))

In [ ]:
with open(filename, 'rb') as handle:
        model = pickle.load(handle)

In [ ]:
X_test[135]

In [ ]:
model.predict(X_test[40].reshape(-1,11))

In [ ]:
#création du excel pour visualiser sur qu'elle facture il c'est tromper

In [ ]:
test_df.to_excel('res_excel/test.xlsx')

In [ ]:
df_ypred = pd.DataFrame(y_pred)

In [ ]:
df_ypred.to_excel('res_excel/test_pred.xlsx')

In [ ]:
y_test.to_excel('res_excel/test_image.xlsx')